[project]
name = "stock-market-returns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.11"
dependencies = [
    "dash-bootstrap-components>=2.0.4",
    "dash[compress]<4",
    "httpx>=0.28.1",
    "pandas<3",
    "plotly>=6.5.2",
    "python-calamine>=0.6.1",
    "scipy>=1.17.0",
    "yfinance>=1.1.0",
    "polars>=1.38.0",
    "pyarrow>=23.0.0",
    "fastexcel>=0.19.0",
    "lxml>=6.0.2",
    "numba>=0.63.1",
    "sdmx1>=2.25.1",
]

[dependency-groups]
dev = [
    "geckodriver>=0.0.1",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "nbformat>=5.10.4",
    "ruff>=0.15.0",
    "seaborn>=0.13.2",
    "selenium>=4.40.0",
    "snakeviz>=2.2.2",
]
prod = [
    "gunicorn>=25.0.1",
]
