[project]
name = "stock-market-returns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.11"
dependencies = [
    "dash-bootstrap-components>=2.0.4",
    "dash[compress]>=3.3.0",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "python-calamine>=0.6.1",
    "requests>=2.32.5",
    "scipy>=1.16.3",
    "yfinance>=0.2.66",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "fastexcel>=0.18.0",
    "lxml>=6.0.2",
    "numba>=0.63.1",
]

[dependency-groups]
dev = [
    "geckodriver>=0.0.1",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "nbformat>=5.10.4",
    "seaborn>=0.13.2",
    "selenium>=4.39.0",
    "snakeviz>=2.2.2",
]
prod = [
    "gunicorn>=23.0.0",
]
